[package]
name = "gamedig"
version = "0.0.2"
edition = "2021"
authors = ["CosminPerRam [cosmin.p@live.com]", "node-GameDig [https://github.com/gamedig/node-gamedig]"]
license = "MIT"
description = "Check out servers with this."
homepage = "https://github.com/CosminPerRam/rust-gamedig"
documentation = "https://docs.rs/gamedig/latest/gamedig/"
repository = "https://github.com/CosminPerRam/rust-gamedig"
readme = "README.md"
keywords = ["server", "verify", "game", "check", "status"]

[package.metadata]
msrv = "1.58.1"

[dependencies]
crc32fast = "1.3.2"
bzip2-rs = "0.1.2"
